package com.web.FinalProject.mapper;

import com.web.FinalProject.model.Brand;
import com.web.FinalProject.model.BrandExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface BrandMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table brand
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	long countByExample(BrandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table brand
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	int deleteByExample(BrandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table brand
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	int deleteByPrimaryKey(Integer idBrand);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table brand
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	int insert(Brand row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table brand
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	int insertSelective(Brand row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table brand
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	List<Brand> selectByExample(BrandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table brand
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	Brand selectByPrimaryKey(Integer idBrand);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table brand
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") Brand row, @Param("example") BrandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table brand
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	int updateByExample(@Param("row") Brand row, @Param("example") BrandExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table brand
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	int updateByPrimaryKeySelective(Brand row);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table brand
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	int updateByPrimaryKey(Brand row);

	List<Map<String, Object>> getIdBrandName(String brand_name);

}