package com.web.FinalProject.mapper;

import com.web.FinalProject.model.Cart;
import com.web.FinalProject.model.CartExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface CartMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	long countByExample(CartExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	int deleteByExample(CartExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	int deleteByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	int insert(Cart row);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	int insertSelective(Cart row);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	List<Cart> selectByExample(CartExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	Cart selectByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") Cart row, @Param("example") CartExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	int updateByExample(@Param("row") Cart row, @Param("example") CartExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	int updateByPrimaryKeySelective(Cart row);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cart
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	int updateByPrimaryKey(Cart row);
	List<Map<String, Object>> getItemCart(Integer user_id);
	List<Map<String, Object>> selectCheckCart(Map<String, Object> param);
	List<Map<String, Object>> selectItemInsertCheckout(Map<String, Object> param);
	List<Map<String, Object>> selectCartByPrimary(Map<String, Object> IDCart);
	List<Map<String, Object>> selectProductCart(Map<String, Object> list);
	int updateCart(Map<String, Object> valueInput);
	int updateCartCheckOut(Map<String, Object> data); 
	

	List<Map<String, Object>> InsertIdCartInCheckout(Integer userId);

	List<Map<String, Object>> getDetailProduct(Integer id);



}