package com.web.FinalProject.mapper;

import com.web.FinalProject.model.Product;
import com.web.FinalProject.model.ProductExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
@Mapper
public interface ProductMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	long countByExample(ProductExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	int deleteByExample(ProductExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	int deleteByPrimaryKey(Integer idProduct);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	int insert(Product row);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	int insertSelective(Product row);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	List<Product> selectByExample(ProductExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	Product selectByPrimaryKey(Integer idProduct);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	int updateByExampleSelective(@Param("row") Product row, @Param("example") ProductExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	int updateByExample(@Param("row") Product row, @Param("example") ProductExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	int updateByPrimaryKeySelective(Product row);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table product
	 * @mbg.generated  Wed May 18 19:20:19 ICT 2022
	 */
	int updateByPrimaryKey(Product row);
	List<Map<String, Object>> getProductByCategory(int id_category);
	List<Map<String, Object>> getProductByBrand(int id_brand);
	List<Map<String, Object>> getProductCart(int id_product);
	List<Map<String, Object>> checkProduct(String product_Name);
	List<Map<String, Object>> selectAllProduct();
	List<Map<String, Object>> selectAllProductUpdate(Integer id_product);




}