package com.web.FinalProject.model;

public class Categories {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.id_categories
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    private Integer idCategories;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.nameCategories
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    private String namecategories;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column categories.active
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    private Integer active;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.id_categories
     *
     * @return the value of categories.id_categories
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    public Integer getIdCategories() {
        return idCategories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.id_categories
     *
     * @param idCategories the value for categories.id_categories
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    public void setIdCategories(Integer idCategories) {
        this.idCategories = idCategories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.nameCategories
     *
     * @return the value of categories.nameCategories
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    public String getNamecategories() {
        return namecategories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.nameCategories
     *
     * @param namecategories the value for categories.nameCategories
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    public void setNamecategories(String namecategories) {
        this.namecategories = namecategories;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column categories.active
     *
     * @return the value of categories.active
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    public Integer getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column categories.active
     *
     * @param active the value for categories.active
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    public void setActive(Integer active) {
        this.active = active;
    }
}