package com.web.FinalProject.model;

public class Product {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id_product
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    private Integer idProduct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.product_Name
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.price
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    private Integer price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id_brand
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    private Integer idBrand;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.id_category
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    private Integer idCategory;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.amout
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    private Integer amout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.color
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    private String color;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.size
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.active
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    private Integer active;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.img
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    private String img;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id_product
     *
     * @return the value of product.id_product
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    public Integer getIdProduct() {
        return idProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id_product
     *
     * @param idProduct the value for product.id_product
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    public void setIdProduct(Integer idProduct) {
        this.idProduct = idProduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.product_Name
     *
     * @return the value of product.product_Name
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.product_Name
     *
     * @param productName the value for product.product_Name
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    public void setProductName(String productName) {
        this.productName = productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.price
     *
     * @return the value of product.price
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    public Integer getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.price
     *
     * @param price the value for product.price
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    public void setPrice(Integer price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id_brand
     *
     * @return the value of product.id_brand
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    public Integer getIdBrand() {
        return idBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id_brand
     *
     * @param idBrand the value for product.id_brand
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    public void setIdBrand(Integer idBrand) {
        this.idBrand = idBrand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.id_category
     *
     * @return the value of product.id_category
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    public Integer getIdCategory() {
        return idCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.id_category
     *
     * @param idCategory the value for product.id_category
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    public void setIdCategory(Integer idCategory) {
        this.idCategory = idCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.amout
     *
     * @return the value of product.amout
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    public Integer getAmout() {
        return amout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.amout
     *
     * @param amout the value for product.amout
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    public void setAmout(Integer amout) {
        this.amout = amout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.color
     *
     * @return the value of product.color
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.color
     *
     * @param color the value for product.color
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.size
     *
     * @return the value of product.size
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.size
     *
     * @param size the value for product.size
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    public void setSize(String size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.active
     *
     * @return the value of product.active
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    public Integer getActive() {
        return active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.active
     *
     * @param active the value for product.active
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    public void setActive(Integer active) {
        this.active = active;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.img
     *
     * @return the value of product.img
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.img
     *
     * @param img the value for product.img
     *
     * @mbg.generated Sun May 01 22:46:40 ICT 2022
     */
    public void setImg(String img) {
        this.img = img;
    }
}